### ISSUE TITLE
Idea - Publish repo content as a gitbook

### ISSUE THREAD

**Issue by OndrejM** [eclipse/microprofile#13]
Just an idea - we could very easily publish the content of this repository as a gitbook and integrate it into microprofile.io page.

This is how it looks like in gitbooks.io right now: https://microprofile.gitbooks.io/microprofile-documentation

The gitbooks.io book can be linked with a github organization - all org members would be automatically admins and could trigger an update by a PR from this repo (gitbook requires org admin rights to hook into github, which is a noopt with the GH eclipse org)

**Comment by mikecroft** [comment]
How have you found Gitbook working with adoc files? When I try to import an adoc based Gitbook repo, the importer tool doesn't recognise it. I'm not sure whether adoc is perhaps just a second-class citizen for Gitbook or if I was doing something wrong. 

Also, see #11 for an idea I had about simply including the text of proposals within the documentation. This would work with a Jekyll/GitHub Pages based repo (haven't done a POC for it yet), but doesn't seem to work with Gitbook. As @kwsutter mentioned in that issue, it's not a super critical feature and a link to the document would probably suffice. I just like it because it's a neat solution :) 

Happy to stick to "KISS" and keep it simple, though!

**Comment by OndrejM** [comment]
If Jekyll/GitHub pages work nicely, they are probably better than gitbook, as we can apply themes and integrate it into microprofile.io much more easily.

I created the gitbook only to show the potential of the md/adoc files in the repo. I had no problems to build the gitbook from adoc files, it worked seamlessly, I didn't even think about whether it is adoc or md.

If someone can create a POC in Jekyll and GH pages, it would be great. I'd be interested how much effort would it require.

**Comment by OndrejM** [comment]
No longer relevant as we use wiki at https://wiki.eclipse.org/MicroProfile
