### ISSUE TITLE
Should presentation material live in this repository?

### ISSUE THREAD

**Issue by mikecroft** [eclipse/microprofile#16]
We had a repository to hold presentation material that anyone could re-use:
https://github.com/microprofile/microprofile-presentations

It would be a good idea to keep this up, since it's certainly been useful to me in the past. I think that it is useful to at least link to presentation resources, but I would probably prefer having the actual files there too.

In the repo above, the resources are separated by file type. Since everything moves so quickly these days, I propose sorting them by date to make it easy to see where the latest information is, something like this:

```
➜  ~/tmp tree presentations 
presentations
├── 2016
│   └── Q4
│       ├── DevNation2016LigthningTalk.pdf
│       ├── DevNation2016LigthningTalk.pptx
│       ├── JavaOneLaunch2016.pdf
│       └── JavaOneLaunch2016.pptx
└── 2017
    └── Q1
        ├── DevoxxUSBOF.pdf
        └── DevoxxUSBOF.pptx

4 directories, 6 files
```

Dividing by month seems excessive, but since "conference season" seems to be spring/autumn, it makes sense to me to have either Q1/Q2/Q3/Q4 or maybe just H1/H2. Just an idea at this point.

**Comment by karianna** [comment]
Seems like a good idea to me, although if we can keep templates separate that would help

**Comment by OndrejM** [comment]
Mike, the repository you linked is still valid and we should continue using it. Because all repositories under the eclipse org have to undergo Eclipse processes and IP checks, we only migrated a few repos under eclipse, the rest of the repos under the microprofile org are still valid.

For a presentation repo, I can't even imagine that all the presentations in the repo undergo the Eclipse processes, and if they do, it would seriously limit anyone who'd like to contribute to it, unless they are project contributors or have signed the contrib. agreement

**Comment by OndrejM** [comment]
In #17, I added a reference to the presentation repo and also other repos in the older Microprofile github organization. We should do the suggested refactoring in the presentations repo.

**Comment by mikecroft** [comment]
Agreed @OndrejM - it makes sense to keep presentation resources where they are for now.
