### ISSUE TITLE
Use Maven Parent POM across all MP projects

### ISSUE THREAD

**Issue by radcortez** [eclipse/microprofile#197]
Revive https://github.com/eclipse/microprofile-parent and extract all the common build login to the Parent POM to be reused across all MP projects.

**Comment by radcortez** [comment]
I believe this is done.

**Comment by njr-11** [comment]
> I believe this is done.

I don't think it has been for [MicroProfile Context Propagation](https://github.com/eclipse/microprofile-context-propagation/blob/master/pom.xml) yet.  I remember running into trouble around the end of last year with getting spec approval due to some license file requirements that we were missing from the TCK JavaDoc JAR because we didn't inherit from the common build logic.  In order to get the release out the door, some select lines of code were copied from parent but it was not yet made to use it because we either didn't know what we were doing or because inheriting from it would have required changes to source code that weren't acceptable at that point in the release.

**Comment by radcortez** [comment]
This is complete.
