### ISSUE TITLE
Publish Javadocs for every new release

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile#31]
Add a step into release to generate complete Javadoc of all MicroProfile features and publish it on microprofile.io site. It could also include the specs in HTML form.

**Comment by anthonyvdotbe** [comment]
I agree this should be on microprofile.io, right next to the "Starter".

OpenLiberty does publish [aggregated Javadocs](https://openliberty.io/docs/ref/microprofile/2.2/), but this is vendor-specific and not obvious to find for newcomers. Moreover, they're using a custom doclet and a custom URL syntax for referring to classes/methods (which causes problems with tooling that depends on the default URL syntax).

**Comment by kwsutter** [comment]
We have a PR that pretty much satisfies this older Issue...  Per the discussion between myself and @emattheis, we would like some additional eyes reviewing it before the merge.
https://github.com/eclipse/microprofile/pull/89

Instead of publishing to microprofile.io site, this proposal publishes to the more public javadoc.io site.

**Comment by anthonyvdotbe** [comment]
The last MicroProfile version that has published Javadocs on javadoc.io is 5.0
I've already filed https://github.com/eclipse/microprofile/issues/317 for 6.0, but without any response to date.

Am I just missing something and are Javadocs published somewhere other than javadoc.io nowadays?
Because if not, I'm puzzled that this isn't considered a higher-priority issue. As a Java specification project, having your Javadoc published somewhere seems pretty important.

**Comment by Emily-Jiang** [comment]
done
