### ISSUE TITLE
[Architecture Board] - using CDI in the specs

### ISSUE THREAD

**Issue by OndrejM** [eclipse/microprofile#32]
The following appeared in the minuting minutes of the last Architecture Board on May 31 (I wasn't able to attend because I was at a conference):

> On the CDI dependency, keep in mind that we may want to promote adoption by Spring, Guice, etc., so try to layer the requirements around CDI.

I'm afraid this breaks the CDI-first rule we had until now, which went the other direction - first create an API that uses the full potential of CDI and then think about an alternative API to support usage in Java SE.

I think this decision requires a more through discussion and explanation of the change in the direction of using CDI.

I suggest that the official guideline remains as it was until now, focusing on CDI and adding support for other usecases later (in the same or subsequent versions). Even if we want to support Spring, Guava or Java SE, there's no reason to focus on them first. CDI is part of MicroProfile from day one, it was chosen as the main programming model of MicroProfile in the beginning, and to change that we should have valid and important reasons.

**Comment by starksm64** [comment]
The discussion in the meeting was around how CDI first could be done in a way that did not exclude reuse in non-CDI contexts. I would not say this is an effort to support non-CDI runtimes, rather simply don't exclude possible adoption if there are SPIs that it makes sense to define.

**Comment by jroper** [comment]
To elaborate on what @starksm64 said, we definitely didn't say that any APIs we do should focus on adding support for Spring or Guice. It was more a matter of clarifying what CDI first means. We wanted to emphasise that it doesn't mean automatically adding a dependency or requirement for CDI, especially to the exclusion of other DI frameworks. It means that features should be designed first with using them in combination with CDI in mind, but, if it doesn't impede on the ability to deliver a cohesive spec, CDI dependent features should be layered on, rather than required as a fundamental dependency. For example, the CDI support provided by MicroProfile Config is layered on top - MicroProfile Config can be used completely independently of CDI.

In some cases it may make sense to harness the full potential of CDI in a fundamental way in a spec, in the discussion we definitely didn't say that shouldn't be done. But, in most, if not all of the specs created so far, that hasn't been the case, there's been no reason to fundamentally tie any of the specs created so far to CDI.

**Comment by OndrejM** [comment]
Thanks, @jroper. But I would argue that MP Config is exactly an example of how CDI-first shouldn't work.

In MP config, all functionality was first designed to work in Java SE environment and only later CDI support was added. If I didn't push for CDI support, MP Config would probably only provide Java SE APIs. When we design the API in layers and begin with a layer that doesn't require CDI then there's high risk that either the CDI API isn't complete or it has serious usability issues.

I agree with the layered approach, but in the way that CDI-based API is always designed first and then sliced off to support less dependencies, such as JSR 330 or Java SE. In my opinion it's better if CDI-based API is top-quality and the API for using without CDI is incomplete or cumbersome than the other way around.

**Comment by OndrejM** [comment]
> there's been no reason to fundamentally tie any of the specs created so far to CDI
I'd argue that the reason for this is exactly that most specs are missing CDI-first approach as there are few CDI experts behind the APIs. So as a result, the specs don't use the full potential of CDI and only provide general purpose API that isn't well integrated with other MP specs.

**Comment by arjantijms** [comment]
@jroper 
>For example, the CDI support provided by MicroProfile Config is layered on top - MicroProfile Config can be used completely independently of CDI.

In that case though there's an extra reason for that, and that's that config has to be usable by CDI extensions themselves before CDI is fully booted.

**Comment by arjantijms** [comment]
>But, in most, if not all of the specs created so far, that hasn't been the case, there's been no reason to fundamentally tie any of the specs created so far to CDI.

I personally think that's the wrong approach. 

CDI is a first class building block of MicroProfile, and building everything strongly with CDI in mind gets you into a certain mindset that makes much better use of CDI and provides you with more elegant and consistent API designs.

If you don't do this, you get into the situation where you're nothing more than an average unexciting common dominator thing. You may be compatible with Spring, but honestly, how many users are going to use say MP JWT with Spring, when Spring already has its own excellent security library? I'd be surprised if that would be 10% of the MP users (probably much less). 

Now we should really design for the 80% or 90% of use cases and not compromise for the 10% or less.

If we continue down this road, someone will say; let's not design for JAX-RS anymore, but let's just design for REST APIs in general so Spring MVC users can use it too. But then someone says; let's design for Servlets only, since there might be someone out there who wants to use the MP specs, but only has a Servlet container and doesn't want to add either the JAX-RS or Spring MVC jars.

Going further down this path, you could question why design for Java only, since there might be a user, deep in the last jungle of Japan, who might want to use the MP specs, and who might be using Python.

While the last example is obviously in jest, I do hope it explains the point of designing for an increasingly less focused common dominator on the base of that there "might" be "someone" who will use it, without much indication let alone prove that that "someone" may actually be there.

**Comment by rmonson** [comment]
I don't normally comment on MicroProfile issues but I did want to add that CDI is fundamental to the future roadmap of Jakarta EE as defined in the roadmap *draft* published by the EE4J PMC.  The roadmap currently states (https://dmitrykornilov.net/2018/05/18/jakarta-ee-technical-directions/):

----------------
### Integration with CDI and Config
Dependency injection and configuration should be included in all projects. It will provide consistency between all Jakarta EE components if they are configured the same way.
----------------

I understand that Jakarta EE integration may not be a first class priority for MicroProfile but I think it is an important end goal, which is why I mention this here.

**Comment by Emily-Jiang** [comment]
Here is what my view:
1. +1 on Ondro. We should do CDI-first approach.
2. For any specs, if use cases arise to support non-CDI scenario, we can then add api/spi.
3. -1 on any hard rules. 
We should consider this case by case. However, when we define specification, simplicity is a must, which is why we should do CDI-first.
Anything to add any unnecessary burdens are road blocks. We should not define some barriers unnecessarily.

**Comment by struberg** [comment]
+1 to @Emily-Jiang If it provides benefits then go CDI. Especially from the integration side some times go only really good when using CDI.
But from the user side of the APIs one most of times can rely on just atinject (JSR-330).
So a lot of those specs could probably even be implemented in Spring to some degree.

**Comment by kenfinnigan** [comment]
I was in the first meeting, and all of you should know from previous threads over the last couple of years that I am a major proponent of CDI APIs first, and maybe only API, for each spec implementation.

I don't see what has been defined as going against that. All it means is that if there isn't a hard requirement for a CDI dependency in a spec, for whatever reason, then don't be adding CDI as a dependency because it's part of the MP base.

Maybe some existing specs don't take fuller advantage of CDI that they could, and we should certainly work towards improving that.

However, as @struberg pointed out in the Architecture call, the majority of specifications that are being "CDI first" may only require the `@Inject` spec, as all the CDI specific bits are part of an implementation as opposed to the API.

**Comment by rmannibucau** [comment]
If all specs don't use CDI then the platform usage is not consistent (you cant use metamodel mutation everywhere for instance, you can't lookup beans the same ways, you don't interact with entry points the same way (inject vs static lookup) etc... ) and at the end the platform is not integrated with the target/enclosing server which means MP is just a drop side by side specs without real integrations which is quite negative for end users at the usage. Also note that it also leads to cases where "it was working", "yes but you added this other spec" cases MP doesn't want probably.

Let's start simple and base all the spec on the same foundation (and align it to JakartaEE which is now CDi driven and no more "by spec" driven to enable a later integration).

**Comment by smillidge** [comment]
+1 on CDI first that was the original vision when launching MicroProfile. MP Config was a specific case due to the need to bootstrap config values so they can be used by the other APIs in CDI extensions.

**Comment by kenfinnigan** [comment]
@rmannibucau what you're not taking into account is that these specs take time to mature, and they initially needed to be developed in an isolated fashion.

When each of these specs were first created there was no real understanding of the best way to integrate them with each other. It's only now that we're starting to see discussions around combining these specifications to provide additional functionality above what a single spec can provide.

I agree that when doing this CDI needs to be at the forefront of how they're integrated, but these type of integration discussions are only just beginning.

**Comment by rmannibucau** [comment]
I can hear that but I assumed CDI was mature enough and there are people enough used to it to do it right directly with the years of feedback we have. In any case if it converges you have my support.

**Comment by arjantijms** [comment]
CDI is certainly mature enough now. People where creating new APIs completely based on Spring beans when those Spring beans were far less mature than CDI is today.

Entire specs have already been created, approved and delivered that are solely based on CDI (JSR 375 for example).

**Comment by kenfinnigan** [comment]
Didn't mean to cause confusion.

I wasn't referring to the maturity of CDI, but of each MP spec. For example, it's difficult to know how Open Tracing and REST Client, or REST Client and Fault Tolerance, can or should interact until each of those specifications has been created and gone through some amount of usage to determine whether they're individual approaches are appropriate or need rework.

Now that most of the MP specs have matured somewhat, we can certainly begin to provide better integration between the different specs where appropriate

**Comment by arjantijms** [comment]
The interaction of (for example) Open Tracing and REST Client is indeed fine to be decided further when there's more information about usage patterns etc available.

But CDI should really be a core building block. As @smillidge mentioned, config was an exception since  it needed a part of that to configure CDI extensions when CDI itself is not fully up. This is what happens in DeltaSpike Config as well.

It should however not mean IMHO that other specs should create a non-CDI API also, using MP Config as a precedent. 

I especially think that the idea to compromise or complicate MP designs to gather for potential .NET or Python users (as an example), who "may" be interested in the spec, is not very realistic. If a spec becomes so popular that .NET users become interested, then there's always an option to create a native .NET variant (see e.g. NHibernate).

**Comment by kenfinnigan** [comment]
I've been a vocal proponent from the very beginning that we shouldn't be doing pure Java APIs for anything other than Config.

In some situations early on I lost that battle, but am hopeful that things will change as time moves on

**Comment by arjantijms** [comment]
Great, thanks! :)

**Comment by kenfinnigan** [comment]
We discussed this during the Architecture call this week and agreed to update https://wiki.eclipse.org/MicroProfile/ArchGuidelines with some verbiage stating that "CDI first design and development" is crucial.

We didn't feel the need to be compatible with non CDI injection frameworks was a big enough reason at this time to only rely on `@Inject`.

This can always be re-evaluated in the future if there's more interest from outside MP
