### ISSUE TITLE
Explicitly include implicit/transitive Java EE dependencies in the MicroProfile specification

### ISSUE THREAD

**Issue by mikecroft** [eclipse/microprofile#54]
In the bi-weekly call today, we were discussing the fact that MicroProfile depends on some Java EE/Jakarta EE APIs and we may well need to consider this fact as we further develop MicroProfile on its own path - separate to, but not in isolation from Jakarta EE.

Way back in 1.0, we explicitly included CDI, JAX-RS and JSON-P. We took it as read (mostly for the conference demo app) that JAXB was present, because it was in Java SE. Given that we have now explicitly included JSON-B and JAXB is no longer in Java SE, is that also a spec we want to explicitly include?

Scott mentioned on the call that the JWT spec uses JAX-B and Mark mentioned that JAX-RS might also use it. We also have things like common annotations which we kind of assume are there.

It would be better to be explicit about everything we require in MicroProfile, in my opinion.

**Comment by rmannibucau** [comment]
Think it is important to NOT include jaxb and no spec really requires it on MP side. JWT does not use it since it only relies on json and jaxrs uses it if present but MP can make it optional since it does its own bundling definition. Since jaxb SE is no more delivered in java and MP does not need it at any level it is likely saner to make it automatically integrated if present but not required. Can also be pushed back to jaxrs to adapt the wording on last java versions.

**Comment by kenfinnigan** [comment]
In today's architecture meeting there was agreement that this issue can now be closed
