### ISSUE TITLE
Evaluate adding EL 3.0 into MicroProfile Platform

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile#56]
I found out that the CDI-API v2.0 maven artifact from MP 2.0 brings in EL-API 3.0. Should we officially add EL into MP 2.0? Does CDI 2.0 use EL and where? Can we use EL in other MP specs?

**Comment by rmannibucau** [comment]
CDI does not need it and EL leads to easy vulnerabilities so probably better to stay off it for now.

**Comment by kenfinnigan** [comment]
Closing. Was discussed during the Architecture call and we didn't see a specific use case for including EL directly into MP

**Comment by kwsutter** [comment]
Found out that we already have MP components that have a dependency on EL 3.0...  Metrics already has a declared dependency.  And, Reactive Messaging is looking to declare a dependency.  Since EL 3.0 was already approved for use by Eclipse, I created a piggy-back CQ to cover our usage:  https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20281

So, now @OndroMih's question is valid...  Since we have declared dependencies, should we officially include it in our base set of Java EE/ Jakarta EE dependencies?

**Comment by rmannibucau** [comment]
No mp component have el dep, it is leaking transitive deps i think

**Comment by kwsutter** [comment]
You are right, @rmannibucau!  The EL 3.0 dependency in Metrics was due to the CDI API.  But, I have still heard that Reactive Messaging might have a direct dependency...  Let's leave this open and see if they respond.  Thanks!

**Comment by rmannibucau** [comment]
Well messaging will not be in mp 2.0 so can be worth another issue but design issues will likely stay :(

**Comment by kwsutter** [comment]
Ahh, right...  Since this was discussed at our recent Architecture Board meeting, I didn't notice the title indicated MP 2.0.  I'll correct that.  It's a general design issue.

**Comment by cescoffier** [comment]
There are no dependency on EL in reactive messaging, and there are no plan to add one.

**Comment by cescoffier** [comment]
Actually, about Reactive Messaging, there is a dependency on EL as a transitive dependency of CDI. So I believe that every project that depends on CDI 2.0 depends on el:

```
\- javax.enterprise:cdi-api:jar:2.0:compile
[INFO]    +- javax.el:javax.el-api:jar:3.0.0:compile
[INFO]    +- javax.interceptor:javax.interceptor-api:jar:1.2:compile
[INFO]    \- javax.inject:javax.inject:jar:1:compile
```

**Comment by rmannibucau** [comment]
Yes and not, the only usages of EL by CDI are BeanManager#getELResolver() and BeanManager#wrapExpressionFactory(EF). If you don't use EL in your app you can safely exclude el-api - this is what geronimo-jcdi - the Apache CDI API bundle - does making it provided by default.

**Comment by cescoffier** [comment]
We definitely don't use it (in Reactive Messaging, I can't say anything for the other spec). So we can safely exclude it. 

Also, a related question, should the dependency on CDI be in the `compile` scope or in the `provided` scope? From the user POV, I would say the `compile` is better as it resolves the transitive.

**Comment by rmannibucau** [comment]
provided, it is brought by the actual runtime (impl/server)

**Comment by cescoffier** [comment]
Thanks @rmannibucau, The Reactive Messaging spec is going to be updated (https://github.com/eclipse/microprofile-reactive-messaging/pull/55).

**Comment by kenfinnigan** [comment]
Maybe we just need guidelines for specs to exclude the EL API from the CDI dependency?

**Comment by rmannibucau** [comment]
@kenfinnigan think it is easy to just exclude it, run all TCK, and see it works :)

**Comment by kwsutter** [comment]
Hi, I've been working with @Emily-Jiang as well on this...  We have determined that EL is a transitive dependency for Reactive Messaging due to the CDI dependency as @cescoffier has already documented.  So, maybe this Issue should be closed once again?

**Comment by cescoffier** [comment]
@kwsutter To be precise, Reactive Messaging does NOT depend on EL anymore, even as a transitive dependency. It's been explicitly excluded.

**Comment by kenfinnigan** [comment]
I think we need to verify/ensure that all specs are excluding EL API from CDI dependency to ensure it doesn't get accidentally used.

This is one of those cases where a parent for all specs would be beneficial

**Comment by Emily-Jiang** [comment]
I would like to understand a bit more on "EL leads to easy vulnerabilities" from @rmannibucau . Can you elaborate a bit more on the vulnerabilities? We normally don't ban APIs if there is a need to bring them in. Are you saying el api is bad and stay away from it? When @kwsutter and I looked at this api, it seems it is a leafy api, which does not drag along other transitive dependencies.

**Comment by kenfinnigan** [comment]
What's the use case that requires it be brought in?

**Comment by rmannibucau** [comment]
@Emily-Jiang before all I will recall there is no MP use case yet about EL but then EL enables to run any code - to summarize it quickly, the 0-day issue is accessible through EL strictly speaking - so if you want to use it for any spec, EL usage must be protected by preventing its usage from any endpoint (including messaging kind of endpoints) so at the end there is no real possible usage since MP is only about exposing things (config, metrics, jwt auth, messaging, etc...) and does not have a backend layer. Also note that even respecting that, it would then be easy to be forbidden and after a few time it would leak in external layers of MP and enable the vulnerability. Finally the last drawback is that EL is quite fat and slow for what it brings, bean validation did that error so I hope MP does not do it. Hope it is clearer.

**Comment by OndroMih** [comment]
If no MP spec uses EL than we should clarify this in guidelines and spec documents. Then it's a useful technical detail to exclude the transitive dep from the maven artifact for those which depend on CDI.
I think it's fair to recommend that no MP spec requires EL unless it's really convenient and useful. 

It should also be clear that MP implementations don't have to support EL despite that it's required by a (small) part of CDI.

**Comment by hutchig** [comment]
I believe that MP has never required total 100% CDI compliance - as a
‘pre-existing’ spec - only the set necessary to pass the (free to run at
the time) MicroProfile TCKs included in a specified MP version.

**Comment by rmannibucau** [comment]
It is a bit more complex, MP requires CDI SE+part of the web to be usable (otherwise no CDI lib can be used in MP ;).
This excludes all the rest where EL is. Now, web part is very unclear (request scope is there but what about sessions, conversations etc... MP makes pretty obvious by construction it must be optional but it is not very clear).

**Comment by kenfinnigan** [comment]
Issues have been created in the specifications utilizing `cdi-api` to exclude `el-api` as per Architecture call yesterday

**Comment by aguibert** [comment]
If we exclude `el-api` from MP dependencies, this could be a breaking change to users, right? They could have a dependency on just one of the MP artifcts, and be getting EL transitively from that and successfully compiling against that API in their app. Then if we exclude this dependencies suddenly apps may fail to compile.

Does this need to wait for the next breaking change release?

**Comment by rmannibucau** [comment]
@aguibert if true then an impl was there - otherwise it would have failed anyway - so the impl must brings the api anyway (+ it would be a good user practise to define it) so no brekaing change :).

**Comment by aguibert** [comment]
right, if people had been compiling their app with el-api today, then their runtime must be providing an implementation anyway.
So removing the dependency wouldn't be a "runtime breaking change" but it could potentially be a "compile-time breaking change"

**Comment by OndroMih** [comment]
It's very easy to solve the compile-time braking change by adding the EL API artifact explicitly, isn't it? Then the users would be in the same situation as before. I wouldn't do anything more than mention this "workaround" in release notes for those who are affected.

**Comment by kenfinnigan** [comment]
Going to close this as we've decided to exclude it from the platform for now
