### ISSUE TITLE
Deprecate reactive stream spec

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile#57]
With java embracing reactive proramming, MP just creates noise with reactive stream operator.. Better would be to remove that spec and provide widely in the platform bridge methods to reactive world like jaxrs did (rx(executor) or unwrap(MyImpl.class)). Also note it makes fault tolerance inconsistent with the platform itself if kept so before adding it as a requirement everywhere, better to ensure the platform consistency and sanity. Note it does not prevent any reactive use case if these small bridge methods are added and even enable more cases (native rxjava etc).

**Comment by jroper** [comment]
So, how would you suggest that someone, given a `Publisher<A>`, convert it to a `Publisher<B>`? Or to make it more concrete, if someone has a websocket which is a `Publisher<ByteBuffer>`, and they want to publish it to a reactive streams based messaging implementation which accepts a `Publisher<Message>`, how would they convert from the first to the second? Because without MicroProfile Reactive Streams Operators, the only way to do so is to bring in a third party API, which would be saying that any Reactive Streams support provided in MicroProfile is unusable just with MicroProfile alone, but needs a third party API to use it. Is that something we want in MicroProfile?

**Comment by rmannibucau** [comment]
@jroper if you assume your Publisher is bridge-able to a java.util.stream, do you still ask the question? likely not ;). No 3rd party and no new API. Sure it is not as rich as RxJava but it is more than enough for Microprofile which has a very low need and does not aim at being a reactive API but only integrating with reactive 3rd party libraries.

**Comment by jroper** [comment]
Publisher is absolutely not bridgeable to `java.util.stream`. What makes you think it is?

**Comment by rmannibucau** [comment]
What microprofile needs is only a way to emit records which is a stream by construction. Everything else can be built on top and is out of scope of microprofile. Also keep in mind MP must enable bridge to other libs - take JAXRS as an example, they successfully did it - so if you want a more advanced reactive API you can still plug it but you don't pollute the default platform with useless things in most cases.

**Comment by jroper** [comment]
`java.util.stream` has no support for backpressure, which is pretty important for handling IO, where a fast streaming connection can cause a server to run out of memory.

Now if you want to appeal to someone else's knowledge, as you are trying to do with JAXRS, I actually had a discussion with Brian Goetz earlier this year, where I asked him whether he thought `java.util.stream` could be used to also build graphs for Reactive Streams, as you're suggesting. This was his response:

> So, I’m not convinced it makes sense to try to make a single API that covers both in-memory/data-parallel/finite and infinite/reactive; I think the two use cases are different enough that they surely would fight.  However, I think there’s totally room for a reactive API that looks *a lot like* streams, since many of the operations (filter, map) are common.  So I wouldn’t try to extend streams, as much as borrow idioms and terminology.

This is exactly what we've done in MicroProfile Reactive Streams Operators.

**Comment by rmannibucau** [comment]
@jroper nop, what I strongly disagree in your answer is not that but that "build graphs for Reactive Streams" is not a goal of Microprofile platform. It is not consistent to put that in microprofile itself.

**Comment by jroper** [comment]
Ok, but then you still haven't answered the original question, as MicroProfile APIs adopt Reactive Streams more, they are going to have cases where users need to plumb streams from one place to another, transforming the messages along the way. How will a user do that?

**Comment by rmannibucau** [comment]
"MicroProfile APIs adopt Reactive Streams" is not true, no spec requires it today (for good reasons) and it is important this use case is enabled but not core of the Microprofile spec otherwise we'll loose users and block adoption. This is the whole point. Keep the core platform sane, simple and efficient. Client API has timeouts and error handlers, server as well with completionstage and it is all it requires. Everything else can be done unwrapping API as will depending the user stack. Having a new API in between which still requires to unwrap to benefit of its custom stack or polluting the simple cases would just be a defeat for the platform IMHO.

**Comment by jroper** [comment]
Well, I strongly disagree with that, and I think the rest of the Java ecosystem does too - look at the headline feature of Spring 5 (reactive streams support literally everywhere), several core JDK APIs are adopting it, and outside of standards, more libraries/frameworks seem to support it than don't these days. With such level of adoption, we'll lose users if we don't support it.

**Comment by OndrejM** [comment]
@rmannibucau I really don't get your arguments. Can you explain the following?
> it is important this use case is enabled but not core of the Microprofile spec otherwise we'll loose users and block adoption.
I really don't understand why an additional common API for building reactive pipelines like MP operators could block adoption. It's just an alternative for those who want to build reactive, resilient and responsive apps. Those wouldn't need to add RxJava or a similar library. Those who don't care wouldn't use it at all and have more traditional options.

> provide widely in the platform bridge methods to reactive world
JAX-RS adopts Java SE CompletionStage and allows plugging in reactive libraries. However, JAX-RS only provides a single response and not a stream. There's nothing that would provide reactive streams in Java SE. `java.util.Stream` is similar but limited only to pull pattern without back pressure support. It's completely sane to provide a common reactive API in MicroProfile AND also allow plugging in other reactive libraries like RxJava. But the latter doesn't need to be in the scope of v1.0. If there's no common API, MP users would be forced to depend on an external library like RxJava to connect various parts of MP components in the future.

 > Everything else can be built on top and is out of scope of microprofile. 
The scope of MicroProfile isn't only Microservices, although that has been a big part of its focus. The real scope of MicroProfile is to innovate while standardizing. I think that since there's no common or standard API for reactive operators, this spec meets the scope very well. Is there any other scope you have in mind?

**Comment by rmannibucau** [comment]
@OndrejM the point is that you can keep the reactive side of the specs without requiring reactive-streams spec at all. Look how implementations make MP config optional even when config is needed by implementations (jwt-auth, metrics, etc...). Any additional dep in the spec which is not part of the core platform (CDI/JAXRS/JSONP/JSONB) is not desired in general. Adding any required dep should only be done at the price of a mandatory and killing feature. Reactivity is not that as prooved by JAX-RS.

1. Is the platform already reactive? yes.
2. Does the platform should enable users to write reactive flows? probably
3. Is 2 a target of MP? Clearly not, the goal is to provide a functional and efficient/productive solution, not to complexify JakartaEE in a forced way which is what reactive-streams is preparing.

**Comment by jroper** [comment]
This issue has been discussed in the architecture call, and on the mailing list, and the overwhelming consensus is that MicroProfile Reactive Streams Operators spec is valuable and should not be deprecated, so I'm closing this issue. See https://groups.google.com/d/msg/microprofile/bDSnQT6-5UQ/k5T-beIxAAAJ for more details.
