### ISSUE TITLE
Ensure MP is unified as a platform

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile#61]
Currently each spec imposes its stack (typically openapi has yaml for instance and no other spec uses it, even config). While it overlaps with ee it is acceptable but in other cases it create a new stack and dev model which is neither convenient nor consistent for end users. It also has impact on end user deliveries which are undesirable (like managing some CVE ;)).

Goal of this task is to explicit that all features requiring libs outside default mp stack must be optional.

Also this ticket must ensure the platform consistency at design level (metrics and health are likely unified as a - cdi - bus api / typing events to be user driven instead of mapping an API per k8s need).

These tasks are key to make MP elected as usable by end users and one day merged with jakarta ee - if not this means MP is just yet another lib which is not the current message.

**Comment by kenfinnigan** [comment]
In todays MP Architecture call it was agreed that JSON should be the default data format for any output. However, there will be exceptions where external or industry standards dictate a preference for a different format. For example, OpenAPI defines YAML and Metrics defines Prometheus

**Comment by rmannibucau** [comment]
This is not statisfying and still inconsistent which means MP does not build a platform but vendors libraries.

Please reconsider it since

1. All not json output can be optional
2. There is no need of any default (you can use accept header or another endpoint like openapi.json)
3. All these choices are vendor specific which has no link with a spec or portable api as microprofile claims being

Please fix that way to proceed

**Comment by OndrejM** [comment]
MicroProfile doesn't aspire to become a stable standard like JavaEE, @rmannibucau. Although I agree with your opionion if it targeted to become a standard, I'm more relaxed because MP's target is something else - a collaborative innovation. And innovation has to be proved in practice. So initially MP specs adopted formats commonly used in their area, instead of just a "standard" format that no tools support. In the future, once MP becomes more relevant and libearies will support its standard formats, other formats like YAML or prometheus can be deprecated. I don't feel we can afford that yet. So instead of try to push for this here, try to push library maintainers to support standard MP formats base on JSON.

**Comment by rmannibucau** [comment]
I can hear that but it means it does not have to be open source, in any fondation etc...

All spec are impl in less than a week and just copy standards so no innovation too. If not about any standardization, what's the point? Means users cant use it so it is a sandbox? Let's rename it if so, jakarta-sandbox?
